### ISSUE TITLE
when I use the mod with a texturepack the glass pane is bugged and still shows the buttom layers.

### ISSUE THREAD

**Issue by TheNukeLore** [PepperCode1/ConnectedTexturesMod-Fabric#1]

**Comment by PepperCode1** [comment]
Could you provide the resource pack zip or link? This seems like intended behavior because vanilla glass pane models do not cull top and bottom faces.

**Comment by PepperCode1** [comment]
I'm closing this issue as the author seemed to have confirmed that there was a misunderstanding and there is actually no bug. If there is a bug, please open another issue.
