### ISSUE TITLE
random crashes with sodium and indium

### ISSUE THREAD

**Issue by mineland-0066** [PepperCode1/ConnectedTexturesMod-Fabric#15]
there seems to be some kind of incompatibility with sodium+indium. the game crashes at random without any warning and it seems to be because of sodium/this mod. if i remove the ctm mod the game runs fine. if i remove sodium the game also runs fine. dunno what it could be, something about the chunk rebuilder acording to the console.
[logs.log](https://github.com/PepperCode1/ConnectedTexturesMod-Fabric/files/6604957/logs.log)
on a related note, before the random crashes there was a weird crash where certain parts of a chunk wouldnt render and if i updated the chunks the game would crash. after that the crashes were instant and that weird half chunk hasnt happened again

**Comment by PepperCode1** [comment]
Please check if this bug is still happening in the 0.5.0 update. Thank you.

**Comment by PepperCode1** [comment]
Also, this seems like it could be a bug with Sodium, so try updating Sodium and Indium as well.

**Comment by mineland-0066** [comment]
oh wow i thought the mod was abandoned. glad to see its still alive. im going to try check the latest sodium and indium 1.17 builds to see if they work together.

**Comment by mineland-0066** [comment]
it seems that the crashes have been fixed with the latest builds of both sodium and indium in 1.17. havent tested in 1.16 but i might suspect it had to do with me having dashloader installed or idk.
anyways, the issue seems to be fixed
