### ISSUE TITLE
Huge performance impact

### ISSUE THREAD

**Issue by rbits0** [PepperCode1/ConnectedTexturesMod-Fabric#18]
When I am using the Simple CT resource pack on the "Redstone Ready" superflat preset, I go from around 200 fps to 5 fps. This is obviously because of the huge amount of sandstone in the world, and is fixed if I remove sandstone from the resource pack. I don't know if there is a simple way to fix this, but I figured I would submit this issue anyway as I can't see anyone else mentioning this.

**Comment by DragonEggBedrockBreaking** [comment]
I get the same fps with and without the resource pack in the world.

**Comment by PepperCode1** [comment]
Please check if this bug is still happening in the 0.5.0 update. Thank you.

**Comment by rbits0** [comment]
It is much better now. There still is a noticable impact on my framerate (especially with Sodium), but it's definitely playable now.
