### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by edwloef** [PepperCode1/ConnectedTexturesMod-Fabric#19]
Downloaded source, won't build due to inability to compile settings.gradle.

stack trace: https://pastebin.com/SCFBRa3x

**Comment by PepperCode1** [comment]
This issue occurs because the Gradle wrapper version that is used doesn't support Java 16. For now, you can update it manually or use an older Java version, such as 11. This will be fixed soon.
