### ISSUE TITLE
Glass doesn't connect properly

### ISSUE THREAD

**Issue by edwloef** [PepperCode1/ConnectedTexturesMod-Fabric#20]
Uploading 2021-06-21 10-33-17.mp4…

**Comment by edwloef** [comment]
https://user-images.githubusercontent.com/75493688/122732145-462c0600-d27c-11eb-9fc7-13c2967d1d84.mp4

lol video didn't upload

using version 0.4.0 and this texture pack: https://www.curseforge.com/minecraft/texture-packs/simple-ct with sodium and indium

**Comment by Xoouu** [comment]
Question not related to the problem: How do you have no particles when you are breaking a block is it a resource pack or a mod?

**Comment by DragonEggBedrockBreaking** [comment]
> Question not related to the problem: How do you have no particles when you are breaking a block is it a resource pack or a mod?

Idk about them, but I disable block particles with the tweakeroo mod.

**Comment by Xoouu** [comment]
> 
> 
> > Question not related to the problem: How do you have no particles when you are breaking a block is it a resource pack or a mod?
> 
> Idk about them, but I disable block particles with the tweakeroo mod.

Thanks a lot!

**Comment by edwloef** [comment]
> Question not related to the problem: How do you have no particles when you are breaking a block is it a resource pack or a mod?

I do indeed turn them off with tweakeroo, though there most likely are other mods especially for that, if you don't like using it.

**Comment by Xoouu** [comment]
> > Question not related to the problem: How do you have no particles when you are breaking a block is it a resource pack or a mod?
> 
> I do indeed turn them off with tweakeroo, though there most likely are other mods especially for that, if you don't like using it.

Thanks, I did that and works wonders!

**Comment by PepperCode1** [comment]
I have noticed some inexplicable incorrect connections from time to time and while reworking some code, but I've tried debugging a similar connection problem for many weeks and I was not able to solve it. Hopefully the next release works better for you.

**Comment by PepperCode1** [comment]
Please check if this bug is still happening in the 0.5.0 update. Thank you.

**Comment by Lopolin-LP** [comment]
> Please check if this bug is still happening in the 0.5.0 update. Thank you.

It is still happening.
Well... now it doesn't connect stuff at all (on my end.)

**Comment by Lopolin-LP** [comment]
> > Please check if this bug is still happening in the 0.5.0 update. Thank you.
> 
> It is still happening.
> Well... now it doesn't connect stuff at all (on my end.)

Haha, me dum'. Sodium still needs Indium, dunno why i thought it didn't need it anymore...
Umm yes, works _"fine"_ now.
EDIT: **no**. Maybe when loading the World it connects the stuff, even tho the chunk didn't finish loading? When reloading the Texture Packs, the error with the weird connection is (almost) gone...
