### ISSUE TITLE
blocks doesnt connect

### ISSUE THREAD

**Issue by celakk1** [PepperCode1/ConnectedTexturesMod-Fabric#21]
i have the CTMF mod and the textures 
<img width="966" alt="Zrzut ekranu 2021-06-26 o 11 04 23" src="https://user-images.githubusercontent.com/49827604/123508217-49553680-d66e-11eb-836a-b798f8b1806b.png">
and when i turn on these its doesnt connect
this is my mod folder.
<img width="386" alt="Zrzut ekranu 2021-06-26 o 11 05 32" src="https://user-images.githubusercontent.com/49827604/123508241-70ac0380-d66e-11eb-8b04-de417a93428d.png">

**Comment by Shadowevil015** [comment]
Hi! You need [Indium](https://github.com/comp500/Indium/actions) to see connected textures with sodium, If you don't know how to use github actions, you should join the [Discord](https://discord.gg/7rnTYXu), and head over to #sodium-indium-ctm

**Comment by DragonEggBedrockBreaking** [comment]
To use Indium, you also need to update your Sodium version. You seem to have many outdated mods that could cause issues, e.g. the latest versions are Sodium 0.2.0, Sodium Extra 0.3.2, Lithium 0.6.6 and Fabric API 0.36.0

**Comment by celakk1** [comment]
> To use Indium, you also need to update your Sodium version. You seem to have many outdated mods that could cause issues, e.g. the latest versions are Sodium 0.2.0, Sodium Extra 0.3.2, Lithium 0.6.6 and Fabric API 0.36.0

wow 
i tought every mod is up to date
thanks

**Comment by celakk1** [comment]
> Hi! You need [Indium](https://github.com/comp500/Indium/actions) to see connected textures with sodium, If you don't know how to use github actions, you should join the [Discord](https://discord.gg/7rnTYXu), and head over to #sodium-indium-ctm

but idk where to download indium

**Comment by celakk1** [comment]
> Hi! You need [Indium](https://github.com/comp500/Indium/actions) to see connected textures with sodium, If you don't know how to use github actions, you should join the [Discord](https://discord.gg/7rnTYXu), and head over to #sodium-indium-ctm

oh wait i see the gif where to download it

**Comment by celakeniock** [comment]
also indium need to be up to date??

**Comment by celakk1** [comment]
> To use Indium, you also need to update your Sodium version. You seem to have many outdated mods that could cause issues, e.g. the latest versions are Sodium 0.2.0, Sodium Extra 0.3.2, Lithium 0.6.6 and Fabric API 0.36.0

but i dont see a 0.2.0 sodium theres only 0.1.0

edit: i was looking on curseforge

**Comment by celakk1** [comment]
![2021-06-26_11 51 14](https://user-images.githubusercontent.com/49827604/123509293-df8c5b00-d674-11eb-8a47-3fb34c7bdc31.png)
Thank you guys!
