### ISSUE TITLE
CTMF causing crash/bug with Better End

### ISSUE THREAD

**Issue by topbun92** [PepperCode1/ConnectedTexturesMod-Fabric#30]
Iris/Sodium , Indium and fapi all work fine by themselves. them along with better end all work fine together without CTMF. as soon as i get CTMF in the mix i get stuck in a minecraft loading screen loop.
![Iris_Indium bug screenshot](https://user-images.githubusercontent.com/87154955/128238074-aec4bcc4-f86e-4d88-9bdf-ab53dbe3ceca.png)
[Iris_Indium bug.txt](https://github.com/PepperCode1/ConnectedTexturesMod-Fabric/files/6933698/Iris_Indium.bug.txt)

**Comment by Alkaline-Dreams** [comment]
Same error here

**Comment by PepperCode1** [comment]
This is a bug on BetterEnd's side, and it's been fixed in the code. The next full release should be compatible.

**Comment by PepperCode1** [comment]
Note that while 0.5.1 fixes the resource reload loop with BetterEnd present, some of BetterEnd's block models, like for ladders and doors, appear as missing. This will be fixed by the next BetterEnd update.
