### ISSUE TITLE
`Edges` type connector does not return correct submap

### ISSUE THREAD

**Issue by MrJoshuaT** [PepperCode1/ConnectedTexturesMod-Fabric#31]
The TextureEdges.getSubmapId method seems to return the incorrect index for some cases. I've added the `.mcmeta` and `.png` files, and the current result and my fix. The issue seems to stem from incorrect ordering of conditions.

Given a ctm json of:
`{
  "ctm": {
      "ctm_version": 1,
      "type": "edges",
      "textures": [
          "block/coarse_dirt_ctm",
          "block/coarse_dirt_ctm"
      ],
      "extra": {
          "connect_to": [
              { "block": "grass_block" }
          ]
      }
  }
}
`

Given a ctm png of (ignore the horrid png, I just threw it together to see the result):
![coarse_dirt_ctm](https://user-images.githubusercontent.com/1721365/128744649-7aefdb4e-e41a-4fe2-af0a-b7e06deff4c6.png)

It produces an incorrect result of:
![2021-08-09_17 48 37](https://user-images.githubusercontent.com/1721365/128744790-be6edb7f-cc62-4568-9cbd-302f10405de2.png)

Of which the correct should be:
![2021-08-09_17 47 42](https://user-images.githubusercontent.com/1721365/128744822-56aa431f-92ac-4255-b7b9-82e3d09f44c8.png)

**Comment by PepperCode1** [comment]
Fixed with latest commit.
