### ISSUE TITLE
Transparent texture glitches when using CTM with Sodium 0.3.0+build.5 & Indium 1.0.0

### ISSUE THREAD

**Issue by foxdst** [PepperCode1/ConnectedTexturesMod-Fabric#33]
### **Only CTM**
![2021-08-19_10 36 08](https://user-images.githubusercontent.com/42083205/129981712-6116bcd1-b6d8-47b5-88de-543690a9b200.png)

### **CTM + Sodium w/ Indium**
![2021-08-19_10 34 16](https://user-images.githubusercontent.com/42083205/129981714-13b1e022-30d7-4bfc-aff0-2291e5abebcc.png)

Issue persists when only using Sodium.

**Comment by FwuffyPetsOwO** [comment]
This is Sodium's issue, they don't have translucency sorting yet. They know about this issue and it's on their GH.

**Comment by PepperCode1** [comment]
Indeed, this is a Sodium problem. Here is the GitHub issue: CaffeineMC/sodium-fabric#38.
