### ISSUE TITLE
failing to launch

### ISSUE THREAD

**Issue by is-gordon-ramsay** [PepperCode1/ConnectedTexturesMod-Fabric#34]
whenever i try to launch it crashes and says "Could not find required mod: ctm requires {fabric @ [>=0.34.7+1.16]}" along with "Creating Empty clause ?"

**Comment by TropheusJ** [comment]
Install the newest [Fabric API](https://modrinth.com/mod/fabric-api) version for the version of Minecraft you’re trying to run.

**Comment by PepperCode1** [comment]
This is correct, versions 0.5.0+1.16 or higher require Fabric API of at least version 0.34.7. 1.17 versions require 0.34.10 or higher.
