### ISSUE TITLE
Colored glass looks weird with iris+sodium, indium and starlight. I am using my own CTM pack. It happens with almost every shaders, and without any

### ISSUE THREAD

**Issue by Aeldit** [PepperCode1/ConnectedTexturesMod-Fabric#36]
![2021-09-12_19 21 18](https://user-images.githubusercontent.com/81476169/132996878-f8a2b118-2aca-4995-9512-5f55f30c22d6.png)
![2021-09-12_19 21 30](https://user-images.githubusercontent.com/81476169/132996880-57ac00c1-1670-4473-a541-b8661efd2639.png)

(my pack if you want to test to see the issue by yourself: https://www.curseforge.com/minecraft/texture-packs/ctm-optifine-fabric)

**Comment by PepperCode1** [comment]
The color glass itself looks fine to me, so I'll assume you're refering to the water underneath. Try without Sodium, and if it works correctly, then this bug is probably the result of CaffeineMC/sodium-fabric#38.

**Comment by Aeldit** [comment]
Yep that is a sodium bug
