### ISSUE TITLE
Conflict with Better End/BCLIB

### ISSUE THREAD

**Issue by TestSerber** [PepperCode1/ConnectedTexturesMod-Fabric#37]
Better End handles models/textures in a different way causing conflicts.
https://hastebin.com/pukamenowa.less
This causes the textures to appear as missing textures.

This is primarily an issue with Paul's BCLIB Features if you could add support that would be great.

Linked issue
https://github.com/paulevsGitch/BetterEnd/issues/319

**Comment by PepperCode1** [comment]
Try updating to the very latest version of both BCLib and BetterEnd, because I worked with the devs of these mods to resolve this issue a couple months ago.
