### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by machinesmith42** [PepperCode1/ConnectedTexturesMod-Fabric#4]
Using sodium + indium
Glass does not connect at all

**Comment by PepperCode1** [comment]
Unlike Optifine, CTMF does not add default connected textures, such as glass. A good pack that adds connected glass, as well as other textures, is [here](https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm). If you are already using a resource pack that is supposed to add connected glass, post a comment here that contains the pack information and URL/download and I will reopen the issue.
