### ISSUE TITLE
Hay/ Where 1.18.1 version?

### ISSUE THREAD

**Issue by c1oudychan** [PepperCode1/ConnectedTexturesMod-Fabric#41]

**Comment by PepperCode1** [comment]
1.18.1 is unsupported, meaning it will not be getting any future releases. The last 1.18.1 release was 1.1.0+1.18.

**Comment by PepperCode1** [comment]
I have decided that CTMF is discontinued, meaning it will not be receiving any more updates. In the future, I may make an adapter for the CTMF resource pack format for Continuity.
