### ISSUE TITLE
[Feature Request] Add support for "overlay" textures

### ISSUE THREAD

**Issue by MithicSpirit** [PepperCode1/ConnectedTexturesMod-Fabric#6]
As far as I can tell, this mod is currently missing support for `method=overlay`. I am currently using [this texture pack](https://www.curseforge.com/minecraft/texture-packs/lithos-core-32x-1-6-1-11-complete/files/3231833), which is supposed to have overlay textures [like this](https://media.discordapp.net/attachments/813866590281662524/818559540017758218/Overlay_CTM.jpg), but I cannot get them to work on CTMF.

**Comment by PepperCode1** [comment]
That texture pack is meant for Optifine CTM, which this mod doesn't support. Use [Connected Block Textures](https://www.curseforge.com/minecraft/mc-mods/connected-block-textures) for Optifine CTM resource packs instead. If you want to know more about the different CTM formats, check [this mod's CurseForge page](https://www.curseforge.com/minecraft/mc-mods/ctm-fabric).

**Comment by MithicSpirit** [comment]
Ah ok. Thank you for the info.
