### ISSUE TITLE
Some Item in Give Me Hats Cause Game to Crash

### ISSUE THREAD

**Issue by MizBitz** [PepperCode1/ConnectedTexturesMod-Fabric#7]
Good day, I'd like to report an issue with the Mod. So I decided to used the Mod alongside the Modpack called "All of Fabric 3" and every time certain items(ie: Space Helmet & Leprechaun Hat) in the Mod "Give me Hats" is dropped on the ground or if the player dies, the game would crash. Here are the different crash logs that I got when I was testing out the problem and recreating it.

**First Encounter With the Problem**
https://pastebin.com/KH9C1vzz
**Disabled CTM but didn't Restart Minecraft**
https://pastebin.com/Q7KhUxZt
**Restarted the Game after I disabled CTM**
https://pastebin.com/y5xVqcRA

     When I took CTM out of my mods folder, I was able to enter the world where the problem occurred.

**_Specs_**
CPU: AMD a10-9700 APU 4C + 6G
RAM: 8GB 2400mhz
GPU: Integrated Graphics (AMD Radeon R7 Graphics)
OS: Windows 10 Pro 64-Bit(10.0, Build 19042)
_Version of All of Fabric 3: 2.6.10_ (Modifications: I added Sodium and Indium because my potato, or as I would like to call it, My PC, can't handle the mod pack smoothly without those 2 additional mods)

PS: This is what the member of the AOF team said when I asked for help and reported the problem, I understand that this may very well be caused by user error 'cause I'm not smart. Thanks for the time reading and giving attention to this post. Have a good day.
![image](https://user-images.githubusercontent.com/75293671/111500597-21a52700-877f-11eb-8d90-ea62540d709a.png)

**Comment by PepperCode1** [comment]
Thanks for the report. From what I can see "Give me Hats" isn't open source (although they have a GitHub repository it's empty?) so I can't see exactly what it's doing with its item models, which will make solving this a lot harder. Either way, I'll look into it and try to fix the issue.

**Comment by PepperCode1** [comment]
The creator of Give Me Hats has put up the source and fixed the bug in the latest release of the mod (although I haven't tested it myself). I'll leave this issue open for now just in case more related bugs come up and since AOF 3 hasn't updated to the new version yet.

**Comment by PepperCode1** [comment]
It seems like AOF has updated the mod in one of the newer versions, so I will close the issue. If you notice other bugs with this mod, feel free to open another issue.
